export default {
  editorModules: {
    toolbar: [
      [{ header: [1, 2, false] }],
      ["bold", "italic", "underline", "strike", "blockquote"],
      [{ list: "ordered" }, { list: "bullet" }, { indent: "-1" }, { indent: "+1" }],
      ["link", "image"],
      ["clean"],
    ],
  },
  editorFormats: [
    "header",
    "bold",
    "italic",
    "underline",
    "strike",
    "blockquote",
    "list",
    "bullet",
    "indent",
    "link",
    "image",
  ],
  maxWalkInsTimes: [
    { time: "15", label: "15 minutes" },
    { time: "30", label: "30 minutes" },
    { time: "45", label: "45 minutes" },
    { time: "60", label: "1 hours" },
    { time: "75", label: "1 hours 15 minutes" },
    { time: "90", label: "1 hours 30 minutes" },
    { time: "105", label: "1 hours 45 minutes" },
    { time: "120", label: "2 hours" },
    { time: "135", label: "2 hours 15 minutes" },
    { time: "150", label: "2 hours 30 minutes" },
    { time: "165", label: "2 hours 45 minutes" },
    { time: "180", label: "3 hours" },
    { time: "195", label: "3 hours 15 mintues" },
    { time: "210", label: "3 hours 30 minutes" },
    { time: "225", label: "3 hours 45 minutes" },
    { time: "240", label: "4 hours" },
    { time: "255", label: "4 hours 15 minutes" },
    { time: "270", label: "4 hours 30 minutes" },
    { time: "285", label: "4 hours 45 minutes" },
    { time: "300", label: "5 hours" },
    { time: "315", label: "5 hours 15 minutes" },
    { time: "330", label: "5 hours 30 minutes" },
    { time: "345", label: "5 hours 45 minutes" },
    { time: "360", label: "6 hours" },
    { time: "375", label: "6 hours 15 minutes" },
    { time: "390", label: "6 hours 30 minutes" },
    { time: "405", label: "6 hours 45 minutes" },
    { time: "420", label: "7 hours" },
    { time: "435", label: "7 hours 15 minutes" },
    { time: "450", label: "7 hours 30 minutes" },
    { time: "465", label: "7 hours 45 minutes" },
    { time: "480", label: "8 hours" },
  ],
  
  approvalFieldsGeneral: [
    "name",
    "general_contact_first_name",
    "general_contact_last_name",
    "general_contact_email",
    "phone_number",
    "address_1",
    "address_2",
    "city",
    "state",
    "countries",
  ],
  approvalFieldsWebsite: ["url_name", "description"],
  dashboardTabs: [
    { alias: "operations", display_name: "Operations" },
    { alias: "marketing", display_name: "Marketing" },
  ],
  leaseApplicationStatus: {
    NOT_SENT: "not_sent",
    APPLICATION_SENT: "application_sent",
    NEED_REVIEW: "need_review",
    SIGNED: "signed",
    SECURITY_DEPOSIT_RECEIVED: "security_deposit_received",
  }
  
};
